# vi: set ft=ansible :
---
- name: Check current docker-compose version.
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  failed_when: false
  changed_when: false

- block:
    - name: Delete existing docker-compose
      file:
        path: "{{ docker_compose_path }}"
        state: absent

    - name: Install Docker Compose (if configured).
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: "{{ docker_compose_path }}"
        mode: 0755
  when: >
    docker_compose_current_version.rc > 0 or (
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout)
