---
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Make sure that the {{ docker_group }} exists
  group:
    name: "{{ docker_group }}"
    state: present

- name: Add users that are privileged to run docker
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_users is defined

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- import_tasks: docker-compose.yml
  when: docker_install_compose
